$\textbf{Empirical Exercise-Week 5}$  Page 308, Problem 6.29
Let's look at inequality and tax rates on income 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
Tab1 = pd.read_csv('inequality.csv')

In [3]:
Tab1.head(1)

year  aus_gdp  aus_gwth  aus_share  aus_tax  ca_gdp   ca_gwth  ca_share  \
0     1   4910.8  3.038755      11.63     11.1  3357.0 -13.06407      17.6   

   ca_tax  nz_gdp   nz_gwth  nz_share  nz_tax  us_gdp   us_gwth  us_share  \
0     4.2  5128.1 -8.282444     15.47    10.5  5322.7 -4.135091     15.47   

   us_tax  
0    12.0

In [4]:
year = Tab1.iloc[:,0]; share = Tab1.iloc[:,15]; tax = Tab1.iloc[:,16]; growth = Tab1.iloc[:,14]

In [5]:
year1 = np.array(year); share1 = np.array(share); tax1 = np.array(tax); 
growth1 = np.array(growth);

In [6]:
y = np.log(share1);
xx = np.hstack([np.ones((len(y),1)), tax1.reshape(-1,1)])
result1 = sm.OLS(y,xx).fit()
np.array([result1.params, result1.tvalues]).T

array([[ 2.95690397e+00,  7.29519080e+01],
       [-1.50737705e-02, -1.45279253e+01]])

Higher tax rates reduce the share of national income of the top 1%.

In [8]:
xxx = np.hstack([xx, year1.reshape(-1,1), (year1**2).reshape(-1,1)])
result2 = sm.OLS(y,xxx).fit()
np.array([result2.params, result2.tvalues]).T # year 1 is for 1921

array([[ 3.13249341e+00,  7.62058847e+01],
       [-7.98492192e-03, -5.08493024e+00],
       [-2.72166376e-02, -6.71419543e+00],
       [ 3.11041768e-04,  7.31786456e+00]])

In [9]:
year_min = - .5* result2.params[2]/result2.params[3]
year_min

43.75077626180348

Share minimizing year is 1965 since we start at 1921.



95% confidence interval for the share minizing year

In [10]:
[-.5* result2.conf_int()[2,0]/result2.conf_int()[3,0], -.5* result2.conf_int()[2,1]/result2.conf_int()[3,1]]

[77.941977136454, 24.1892346373913]

Confidence interval for share-minimizing years: 1945 and 1999.

In [11]:
xxxx = np.hstack([xxx, growth1.reshape(-1,1)]) # Add a growth term
result3 =sm.OLS(y,xxxx).fit()
np.array([result3.params, result3.tvalues]).T

array([[ 3.12635725e+00,  7.64002889e+01],
       [-8.12252749e-03, -5.21188978e+00],
       [-2.70730890e-02, -6.73868933e+00],
       [ 3.09828487e-04,  7.35538490e+00],
       [ 3.47193632e-03,  1.55257986e+00]])

Growth term is not significant

Find tax rate which would get the share of the top 1% to 12% in 2001.

In [12]:
tax_star = (np.log(12)-result3.params[0] - result3.params[2]*80 - result3.params[3] * (80**2) - result3.params[4]* 3)/result3.params[1]
tax_star

57.730996703451666

Taxes would have to be 58% to get the share of the top 1% down to 12% of income in 2001.

In [13]:
tax_star_min = (np.log(12)-result3.conf_int()[0,0] - result3.conf_int()[2,0]*80 - result3.conf_int()[3,0] * 80**2 - result3.conf_int()[4,0]* 3)/result3.conf_int()[1,0]
tax_star_min

-71.54746078287313

In [14]:
tax_star_max = (np.log(12)-result3.conf_int()[0,1] - result3.conf_int()[2,1]*80 - result3.conf_int()[3,1] * 80**2 - result3.conf_int()[4,1]* 3)/result3.conf_int()[1,1]
tax_star_max

346.98018719492643