$\textbf{Empirical Exercise-Week 3}$  Page 189, Problem 4.27
Let's look at a similar example from your book, related wages to experience in the work force, as well as to gender and racial differences.  It is a larger data set with the same variables.  We are asked to compare regression coefficients for four different groups baased on gender and racial categories.  It is, de facto, an empirical investigation of work-force discrimination. 

You are free to use the LeSage toolbox or the Matlab built-in regress function.


In [11]:
clear all;
clear all
Tab1 = readtable('cps5.csv');
Names = Tab1.Properties.VariableNames;
Names'


ans =

  23x1 cell array

    {'age'      }
    {'asian'    }
    {'black'    }
    {'divorced' }
    {'educ'     }
    {'exper'    }
    {'faminc'   }
    {'female'   }
    {'hrswork'  }
    {'insure'   }
    {'married'  }
    {'mcaid'    }
    {'mcare'    }
    {'metro'    }
    {'midwest'  }
    {'nchild'   }
    {'northeast'}
    {'single'   }
    {'south'    }
    {'union'    }
    {'wage'     }
    {'west'     }
    {'white'    }




In [12]:
Asian = Tab1(:,2); Aframer = Tab1(:,3); exper = Tab1(:,6); female = Tab1(:,8); 
wage = Tab1(:,21); white = Tab1(:,23);  educ = Tab1(:,5);  
single = Tab1(:,18);
who


Your variables are:

Aframer  Asian    Names    Tab1     ans      educ     exper    female   single   wage     white    




In [13]:
Asian1 = table2array(Asian); 
Aframer1= table2array(Aframer); exper1 = table2array(exper); female1 = table2array(female);
wage1 = table2array(wage); white1 = table2array(white);  educ1 = table2array(educ);
single1 = table2array(single);


Now lets do a dummy variable approach related wage to experience but with indicators for various groups.

In [15]:
y = (wage1); 
x = [ones(length(y),1) exper1 educ1 white1 Aframer1 female1 single1];
[Bols Bint Resid Res1 STATS]  = regress(y,x);
[Bols Bint]
STATS


ans =

  -13.0963  -15.2873  -10.9053
    0.1488    0.1242    0.1733
    2.5644    2.4594    2.6694
   -0.5618   -1.8388    0.7152
   -2.7741   -4.3372   -1.2111
   -3.9533   -4.5225   -3.3841
   -2.9436   -3.6561   -2.2310


STATS =

    0.2192  458.2397         0  201.8304




We extract from the data set subsets of data by gender and race (African American and white).

In [16]:
Data1 = [wage1 ones(9799,1) exper1];

WhiteMale = female1(:,1)==0 & white1(:,1)==1;
AframerMale = Aframer1(:,1) == 1 & female1(:,1)==0;
WhiteFemale =  female1(:,1)==1 & white1(:,1)== 1;
AframerFemale = Aframer1(:,1) == 1 & female1(:,1)== 1;

In [17]:
Data_WhiteMale = Data1(WhiteMale,:);
Data_AframerMale = Data1(AframerMale,:);
Data_WhiteFemale = Data1(WhiteFemale,:);
Data_AframerFemale = Data1(AframerFemale,:);

In [18]:
CV_WhiteMale =  100 * std(Data_WhiteMale(:,1))/mean(Data_WhiteMale(:,1));
CV_AframerMale =  100 * std(Data_AframerMale(:,1))/mean(Data_AframerMale(:,1));
CV_WhiteFemale =  100 * std(Data_WhiteFemale(:,1))/mean(Data_WhiteFemale(:,1));
CV_AframerFemale =  100 * std(Data_AframerFemale(:,1))/mean(Data_AframerFemale(:,1));

In [19]:
[CV_WhiteMale CV_AframerMale CV_WhiteFemale CV_AframerFemale]


ans =

   61.0780   56.6434   79.8826   68.7235




We see that white females have greater variation in their wages, then African American females, relative to their male counterparts.

Lets do a regression for each subset, of (wage) on a constant and experience.

In [20]:
yy_WhiteMale = (Data_WhiteMale(:,1)); xx_WhiteMale = Data_WhiteMale(:,2:end);
yy_AframerMale = (Data_AframerMale(:,1)); xx_AframerMale = Data_AframerMale(:,2:end);
yy_WhiteFemale = (Data_WhiteFemale(:,1)); xx_WhiteFemale = Data_WhiteFemale(:,2:end);
yy_AframerFemale = (Data_AframerFemale(:,1)); 
xx_AframerFemale = Data_AframerFemale(:,2:end);


In [23]:
[WhiteMale_B, WhiteMale_Bint] = regress(yy_WhiteMale, xx_WhiteMale);
[WhiteFemale_B, WhiteFemale_Bint] = regress(yy_WhiteFemale, xx_WhiteFemale);
[AframerMale_B AframerMale_Bint] = regress(yy_AframerMale, xx_AframerMale);
[AframerFemale_B AframerFemale_Bint] = regress(yy_AframerFemale, xx_AframerFemale);

Let's look at the confidence intervals for the experience coefficient for the four subsets

In [25]:
[WhiteMale_Bint(2,:); WhiteFemale_Bint(2,:); AframerMale_Bint(2,:); ...
AframerFemale_Bint(2,:)]


ans =

    0.1260    0.1927
    0.0108    0.0986
    0.0226    0.1913
   -0.0094    0.1852




You readily see that while male coefficient is always above that of White Females, but not always above that of African Amerians, both males and females.

In [97]:
save Exercise_Week3