$\textbf{Empirical Exercise-Week 2}$  Page 141, Problem 3.26
Lets look at the example from your book, relating wages to experience in the work force.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
Tab1= pd.read_csv('cps5_small.csv')

In [7]:
Tab1

black  educ  exper  faminc  female  metro  midwest  south   wage  west
0         0    13     45       0       1      1        0      0  44.44     1
1         0    14     25   45351       1      1        1      0  16.00     0
2         0    18     27   91946       1      1        0      0  15.38     0
3         0    13     42   48370       0      1        1      0  13.54     0
4         0    13     41   10000       1      1        0      0  25.00     1
...     ...   ...    ...     ...     ...    ...      ...    ...    ...   ...
1195      0    13     45       0       1      1        0      0  11.00     1
1196      0    16     17   60400       0      1        1      0  21.63     0
1197      1    16     36   69524       1      1        0      0  18.75     0
1198      0    14     17       0       0      1        0      1  18.00     0
1199      0    10     52   61270       0      1        1      0  16.46     0

[1200 rows x 10 columns]

In [3]:
wage = Tab1.iloc[:,8] 
exper = Tab1.iloc[:,2]  
metro = Tab1.iloc[:,5] 
edu = Tab1.iloc[:,1]
wage1 = np.array(wage)
exper1 = np.array(exper)
metro1 = np.array(metro)
edu1 = np.array(edu)

In [4]:
yy = wage1 
xx = sm.add_constant(exper1)   # create regression variabels;
result1 = sm.OLS(yy,xx).fit()


In [12]:
result1.params

array([21.62307479,  0.08629043])

T stat for the coefficient is 2.61. We have 1200 observations and 2 regressors, so we have 1198 degress of freedom. We are asked to do a one-tailed test of signifcance.

In [5]:
from scipy.stats import t
pval1 = t.cdf(result1.tvalues, 1198)
pval1

array([1.        , 0.99544161])

The pval1 gives the area to the left of the distributon. We look at the area to the right, the probability that the null of zero is true even though we reject it.

In [6]:
pval = 1- pval1[1]  #Evaluate the p-value for the reported t-stat, 2.61, at 1198 degrees of freedom
pval

0.004558388246773126

So at a one-tailed 5 percent test, we can reject the null hypothesis that the coefficeint of experience is zero. Next question: extract the data for metro1==1, do a regression for the folks living in a metro area. It is easy, see below

In [7]:
Data = np.hstack([metro1.reshape(-1,1), yy.reshape(-1,1), xx])  # Combine data set with metro1 and the y and x variables
WhichRow = Data[:,0]==1;   # Find indicator for metro1 = 1;
Data1 = Data[WhichRow,1:];   # Extrat the data for metro1 == 1;
yyy = Data1[:,0]; xxx = Data1[:,1:]
result2 = sm.OLS(yyy,xxx).fit()

In [8]:
np.array([result2.params, result2.tvalues]).T

array([[21.88860925, 21.4719512 ],
       [ 0.11280127,  2.93595005]])

We see that living in a metro area has a stronger effect that the total sample. How about the non-metro area?

In [9]:
WhichRow = Data[:,0]==0;   # Find indicator for metro1 = 1;
Data1 = Data[WhichRow,1:];   # Extrat the data for metro1 == 0;
yyyy = Data1[:,0]; xxxx = Data1[:,1:];
result3 = sm.OLS(yyyy,xxxx).fit()

In [10]:
np.array([result3.params, result3.tvalues]).T

array([[1.94103373e+01, 1.30461832e+01],
       [1.32143451e-02, 2.52242552e-01]])

We see that living in a non-metro area means that experience has a much lower effect on wage and the effect is not statistically different from zero. So experience matters a lot more in metro areas than non-metro areas.